services:
  - type: web
    name: lcc-job-portal
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        value: admin@lcc.com
      - key: ADMIN_PASSWORD
        sync: false
